name: test

permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r quote_disp/requirements.txt
          python -m pip install -r quote_gen/requirements.txt
          pip install pytest-cov
      
      - name: Run tests
        run: |
          pytest -v
      
      - name: Build coverage file
        run: |
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
  
      - name: Comment coverage on PR
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Check test results and mark workflow as failed if necessary
        run: |
          if grep -q 'FAILED' pytest-coverage.txt; then
            echo 'Test case failed. Marking workflow as failed.'
            exit 1
          fi